tunnel: whatsapp-service
credentials-file: /home/dd-pc-012/.cloudflared/9b124d22-c76b-422a-a127-27bc04864c05.json

ingress:
  - hostname: wa-api.billing-generator.co.in
    service: http://localhost:3001
  - service: http_status:404